package Utilidades;

import BLL.MyLogBLL;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.os.Environment;

public class ControladorDB extends SQLiteOpenHelper
{
	public static final int DATABASE_SCHEME_VERSION = 307;
	//public static final String DATA_BASE_NAME = "/mnt/sdcard/android/data/com.detesim.app/EvemAppDB.sqlite";
	//public static final String DATA_BASE_NAME = Environment.getExternalStorageDirectory().getPath() + "/android/data/com.detesim.venderunilever/AppVenderUnileverDB.sqlite";
	public static final String DATA_BASE_NAME = "AppVenderUnileverDB.sqlite";

	MyLogBLL myLog = new MyLogBLL();
	
	public ControladorDB(Context context) 
	{
		super(context, DATA_BASE_NAME, null, DATABASE_SCHEME_VERSION);
	}
	
	public boolean DeleteDB(Context context)
	{
		try
		{
			context.deleteDatabase(DATA_BASE_NAME);
			return true;
		}
		catch(Exception localException)
		{
			if(localException.getMessage() == null || localException.getMessage().isEmpty())
			{
        		myLog.InsertarLog("App",this.toString(),1,"Error al borrar la base de datos: vacio");
			}
			else
			{
				myLog.InsertarLog("App",this.toString(),1,"Error al borrar la base de datos: " + localException.getMessage());
			}
			return false;
		}
	}

	@Override
	public void onCreate(SQLiteDatabase db) 
	{
		db.execSQL(AdministradorDB.LOGINEMPLEADO_TABLE_CREATE);
		db.execSQL(AdministradorDB.SINCRONIZACIONDATOS_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTEPREVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTEVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROVEEDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRECIOLISTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAPRODUCTOTEMP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.ALMACEN_TABLE_CREATE);
		db.execSQL(AdministradorDB.ALMACENPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.MOTIVONOENTREGA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTADIST_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAPRODUCTODIST_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTAPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTAPRODUCTOTEMP_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTAPRODUCTOTEMPDELETED_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAENTREGA_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTAPRODUCTOTEMPNOENTREGA_TABLE_CREATE);
		db.execSQL(AdministradorDB.DEVOLUCIONDISTRIBUIDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.DEVOLUCIONDISTRIBUIDORPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCION_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCIONPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTE_TABLE_CREATE);
		db.execSQL(AdministradorDB.TIPONEGOCIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.ZONA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTEFOTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.RUTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.EXPEDIDO_TABLE_CREATE);
		db.execSQL(AdministradorDB.TIPOCALLE_TABLE_CREATE);
		db.execSQL(AdministradorDB.DIASEMANA_TABLE_CREATE);
		db.execSQL(AdministradorDB.LOG_TABLE_CREATE);
		db.execSQL(AdministradorDB.PARAMETROGENERAL_TABLE_CREATE);
		db.execSQL(AdministradorDB.CIERREPREVENTISTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.DEVOLUCIONDISTRIBUIDORPRODUCTOTEMP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRODUCTOCOSTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.ROL_TABLE_CREATE);
		db.execSQL(AdministradorDB.AVANCEVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.SINCRONIZACIONVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CATEGORIA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTENIT_TABLE_CREATE);
		db.execSQL(AdministradorDB.MOTIVONOATENCION_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTENOATENDIDO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROVEEDORPRECIOLISTAMARGEN_TABLE_CREATE);
		db.execSQL(AdministradorDB.DOSIFICACION_TABLE_CREATE);
		db.execSQL(AdministradorDB.FACTURA_TABLE_CREATE);
		db.execSQL(AdministradorDB.FACTURAPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCIONPRECIOLISTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.DATOSFACTURA_TABLE_CREATE);
		db.execSQL(AdministradorDB.EMPLEADO_TABLE_CREATE);
		db.execSQL(AdministradorDB.IMPRESORA_TABLE_CREATE);
		db.execSQL(AdministradorDB.APKRUTACLIENTE_TABLE_CREATE);
		db.execSQL(AdministradorDB.CIERREDISTRIBUIDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCIONCOSTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCIONPRECIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.APKDISTRUTACLIENTE_TABLE_CREATE);
		db.execSQL(AdministradorDB.COBROPENDIENTE_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTADIRECTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTADIRECTAPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTADIRECTAPRODUCTOTEMP_TABLE_CREATE);
		db.execSQL(AdministradorDB.DISTRIBUIDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTABONIFICACION_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTABONIFICACION_TABLE_CREATE);
		db.execSQL(AdministradorDB.AVANCEDISTRIBUCION_TABLE_CREATE);
		db.execSQL(AdministradorDB.MERCADO_TABLE_CREATE);
		db.execSQL(AdministradorDB.ALMACENPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.ALMACENPOPPRODUCTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.CATEGORIAPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRODUCTOPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAPRODUCTOPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENTAPRODUCTOPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRODUCTOPOPCOSTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRODUCTOCAMBIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTAPRODUCTOCAMBIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.MOTIVOCAMBIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PREVENTACAMBIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.DOSIFICACIONPROVEEDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.DESCUENTO2_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTECENSO_TABLE_CREATE);
		db.execSQL(AdministradorDB.MOTIVOELIMINACIONMATCH_TABLE_CREATE);
		db.execSQL(AdministradorDB.ULTIMACOORDENADA_TABLE_CREATE);
		db.execSQL(AdministradorDB.TIPONIT_TABLE_CREATE);
		db.execSQL(AdministradorDB.CONDICIONTRIBUTARIA_TABLE_CREATE);
		db.execSQL(AdministradorDB.ENCUESTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.ENCUESTADETALLE_TABLE_CREATE);
		db.execSQL(AdministradorDB.ENCUESTARESPUESTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.ENCUESTALISTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTEENCUESTADO_TABLE_CREATE);
		db.execSQL(AdministradorDB.AVANCEVENTAVENDEDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.MOTIVOPOP_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROMOCIONTIPONEGOCIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.ZONAVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.ZONAMERCADO_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTECOBRANZA_TABLE_CREATE);
		db.execSQL(AdministradorDB.METASAP_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTENROFOTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.FOTOCATEGORIA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CIUDAD_TABLE_CREATE);
		db.execSQL(AdministradorDB.PROVINCIA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRECIOLISTANOMBRE_TABLE_CREATE);
		db.execSQL(AdministradorDB.RUTAVENDEDOR_TABLE_CREATE);
		db.execSQL(AdministradorDB.VENDEDORZONAVENTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.ASIGNACIONRUTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CANALRUTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.CANALRUTAPRECIO_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRONTOPAGOUNI_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRONTOPAGOJERARQUIA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRONTOPAGOCANALRUTA_TABLE_CREATE);
		db.execSQL(AdministradorDB.PRONTOPAGOCLIENTE_TABLE_CREATE);
		db.execSQL(AdministradorDB.DRAREBATESALDO_TABLE_CREATE);
		db.execSQL(AdministradorDB.RELEVAMIENTO_TABLE_CREATE);
		db.execSQL(AdministradorDB.RELEVAMIENTODETALLE_TABLE_CREATE);
		db.execSQL(AdministradorDB.CLIENTEDATOSVENTA_TABLE_CREATE);
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) 
	{
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.LOGINEMPLEADO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.SINCRONIZACIONDATOS_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTEPREVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTEVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROVEEDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRECIOLISTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAPRODUCTOTEMP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ALMACEN_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ALMACENPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MOTIVONOENTREGA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTADIST_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAPRODUCTODIST_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTAPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTAPRODUCTOTEMP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTAPRODUCTOTEMPDELETED_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAENTREGA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTAPRODUCTOTEMPNOENTREGA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DEVOLUCIONDISTRIBUIDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DEVOLUCIONDISTRIBUIDORPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCIONPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.TIPONEGOCIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ZONA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTEFOTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.RUTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.EXPEDIDO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.TIPOCALLE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DIASEMANA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.LOG_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PARAMETROGENERAL_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CIERREPREVENTISTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DEVOLUCIONDISTRIBUIDORPRODUCTOTEMP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRODUCTOCOSTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ROL_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.AVANCEVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.SINCRONIZACIONVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CATEGORIA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTENIT_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MOTIVONOATENCION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTENOATENDIDO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROVEEDORPRECIOLISTAMARGEN_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DOSIFICACION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.FACTURA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.FACTURAPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCIONPRECIOLISTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DATOSFACTURA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.EMPLEADO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.IMPRESORA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.APKRUTACLIENTE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CIERREDISTRIBUIDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCIONCOSTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCIONPRECIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.APKDISTRUTACLIENTE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.COBROPENDIENTE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTADIRECTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTADIRECTAPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTADIRECTAPRODUCTOTEMP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DISTRIBUIDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTABONIFICACION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTABONIFICACION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.AVANCEDISTRIBUCION_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MERCADO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ALMACENPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ALMACENPOPPRODUCTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CATEGORIAPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRODUCTOPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAPRODUCTOPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENTAPRODUCTOPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRODUCTOPOPCOSTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRODUCTOCAMBIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTAPRODUCTOCAMBIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MOTIVOCAMBIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PREVENTACAMBIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DOSIFICACIONPROVEEDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DESCUENTO2_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTECENSO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MOTIVOELIMINACIONMATCH_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ULTIMACOORDENADA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.TIPONIT_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CONDICIONTRIBUTARIA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ENCUESTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ENCUESTADETALLE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ENCUESTARESPUESTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ENCUESTALISTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTEENCUESTADO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.AVANCEVENTAVENDEDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.MOTIVOPOP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROMOCIONTIPONEGOCIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ZONAVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ZONAMERCADO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTECOBRANZA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.METASAP_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTENROFOTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.FOTOCATEGORIA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CIUDAD_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PROVINCIA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRECIOLISTANOMBRE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.RUTAVENDEDOR_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.VENDEDORZONAVENTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.ASIGNACIONRUTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CANALRUTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CANALRUTAPRECIO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRONTOPAGOUNI_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRONTOPAGOJERARQUIA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRONTOPAGOCANALRUTA_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.PRONTOPAGOCLIENTE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.DRAREBATESALDO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.RELEVAMIENTO_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.RELEVAMIENTODETALLE_TABLE_NAME);
		db.execSQL("DROP TABLE IF EXISTS " + AdministradorDB.CLIENTEDATOSVENTA_TABLE_NAME);
		onCreate(db);
	}
	
}
